### ISSUE TITLE
Long character and underscore is cut off when font size is set to 12

### ISSUE THREAD

**Issue by budimanjojo** [contour-terminal/contour#1603]
### Contour Terminal version

0.4.3

### Installer source

something else (please specify below)

### Operating System

Ubuntu Linux with Nix

### Architecture

x86-64

### Steps to reproduce

Have `profiles.main.font.size` set to `12` with `UbuntuMono Nerd Font`.

### Expected Behavior

Should display fine

### Actual Behavior

The font is cut off, characters like `g`, `q`, `p`, and `_` are displayed incorrectly. Look at the screenshot below.
![image](https://github.com/user-attachments/assets/c093f1f6-4ecc-4eb7-9a8c-2138867cd604)

### Additional notes

Setting the font to `12.1` fixed this issue. I believe this should also only happen with some fonts (mine being UbuntuMono Nerd Font). This issue doesn't happen with other terminal emulators (tested with Alacritty, Wezterm, Gnome-terminal).

**Comment by Yaraslaut** [comment]
Hi, few font related bugs where fixed in 0.5 release, can you please check this bug in the latest release?

**Comment by budimanjojo** [comment]
Okay I'll try to build the latest version with Nix and report back. Thank you!

**Comment by budimanjojo** [comment]
Apologize for the delay. I couldn't build `contour` at all on my 16GB RAM machine, it keeps killing my entire system on 79% with 100% memory usage. So I decided to run the `contour-0.5.0.7168-fix.AppImage` from the release assets. The bug still persists though. The font is still cut off with `12` font size.

**Comment by Yaraslaut** [comment]
> Apologize for the delay. I couldn't build `contour` at all on my 16GB RAM machine, it keeps killing my entire system on 79% with 100% memory usage. So I decided to run the `contour-0.5.0.7168-fix.AppImage` from the release assets. The bug still persists though. The font is still cut off with `12` font size.

I think at some point gcc was broken, somewhere around gcc 13, with gcc 14 everything is alright, and clang is usually more reliable as well, thanks for trying out, i will try to reproduce it on my system

**Comment by jg1uaa** [comment]
Hello, I found this issue with [VLGothic](https://github.com/daisukesuzuki/VLGothic/releases/tag/20230918)(family: vlgothic)
![vl](https://github.com/user-attachments/assets/84e31845-af4d-4029-a6a0-b824538c7df4)
 and [mixedfont-mplus-ipa](https://ja.osdn.net/projects/mix-mplus-ipa/releases/p4841)(family: ipagothic). both fontsize (size) is 10.5.
![ipa](https://github.com/user-attachments/assets/f8e1a8b0-a84e-4be6-811d-9e369685a053)

Bitmap font from mixedfont-mplus-ipa's IPAGothic looks quite cool for me but only underscore is not displayed. I like VLGothic too but this is hard to use with contour-0.5.0.7168. I hope current version might be fixed this problem.
